### PR TITLE
Dca remarks

### PR DESCRIPTION
**Pull request by gppezzi**

### CODE REVIEW

**Comment by gppezzi** [comment]
Hi @gbalduzz, I've issued this PR to your branch with the remarks I've made on your original version. 

Could you please check and, if you agree, merge this so that we can continue the review process on the EasyBuild repository?

Thanks, 
G.

**Comment by gbalduzz** [comment]
I agree with the changes and merged them.
I have a question for you: Dca does depend on cuda-toolkit as an external
dependency (compiling cuda is very platform dependent). The major version
must be 7, but the project results should not depend on the minor version.
Is there a way to substitute the minor version with a wildcard or use
anything greater than a certain value? Would this even be a good practice?
Cheers, G.B.

**Comment by gppezzi** [comment]
@gbalduzz Using wildcards for version IMO is not good practice concerning reproducibility, your build might fail if the minor version suddenly changes and you might need to invest quite some time to debug that.

But I understand that you would like to avoid having two different easyconfig files just because of a different minor version and I don't think that easybuild currently supports wildcards. 

If you think it is worth investing some time on implementing that option, you can open an issue on [this repo](https://github.com/hpcugent/easybuild-framework) and we can discuss if there's a solution for cuda (maybe adding some extra info on the external metadata?). For example, it would be nice to just change the external metadata file to specify the system dependent version, and only pin the major version on the easyconfig file.

One last comment: I suppose that you also have to modify the external metadata file to add the cuda version available on Titan? If so, it would be nice that you (or @uhaehner) could contribute back that entry with a PR against [this file](https://github.com/hpcugent/easybuild-framework/blob/develop/etc/cray_external_modules_metadata.cfg)

**Comment by ubulling** [comment]
@gppezzi Done.
https://github.com/hpcugent/easybuild-framework/pull/1720

**Pull request merged**
